fix basepower scaling in loads
NREL-Sienna/PowerSimulationsDynamics.jl pull request #331
Opened 2023-06-08 20:10 UTC by m-bossart

- Scales the base power for loads so that the base power of the load can be different than the system base. 
- Test includes a simulation with `LoadTrip `and `LoadChange` to ensure the scaling is handled in the perturbations as well.

2023-06-08 20:35 UTC, jd-lara commented on src/base/device_wrapper.jl
> +    sys_base_power,
```suggestion
    sys_base_power::Float64,
```

2023-06-08 20:36 UTC, jd-lara commented on src/base/device_wrapper.jl
> +            P_power += PSY.get_active_power(ld) * (base_power / sys_base_power)
you could add this as a precalculated value at the top

2023-06-08 20:36 UTC, jd-lara commented on src/base/device_wrapper.jl
>          if isa(ld, PSY.PowerLoad)
```suggestion
        factor = (base_power / sys_base_power)
        if isa(ld, PSY.PowerLoad)
```

2023-06-08 20:37 UTC, jd-lara requested changes
Added some minor change requests

2023-06-09 08:51 UTC, m-bossart commented
I addressed the requested changes

2023-06-23 21:25 UTC, jd-lara approved these changes

2023-06-23 21:26 UTC, merged